epochs: 30
model:
  embed_dim: 384
  return_attention: true
optimizer:
  lr: 0.0001
scheduler:
  steps_per_epoch: 100
  anneal_strategy: "cos"
  max_lr: 0.0001
  epochs: 30
batch_size: 32
train_params:
  log_audio: true
  logging_step: 1
  checkpoint_interval: 1000
wandb_project: tts_hw